Features
wadaudzai/react-todo-app pull request #1
Opened 2022-09-13 18:34 UTC by wadaudzai

Dear Reviewer,

This project was created to display a todo list. In which you can add remove and edit tasks. Please give it your kind review. Thanks for your time.

Regards,

2022-09-16 22:02 UTC, angeluray requested changes
# Hey Good Micronaut :wave:

![68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f574770523531743971623739534e464f74732f67697068792e676966](https://user-images.githubusercontent.com/93039359/190567385-8e7bb3c0-7d3b-4d25-8385-61d173233786.gif)

# Required Changes :recycle:
    
   - **Please check the comments below**
    
## Highlights :1st_place_medal:

:heavy_check_mark: Following Git Flow
:heavy_check_mark: Descriptive PR Title
:heavy_check_mark: Descriptive PR Summary

Good job on implementing some of the requirements, there are some issues that you still need to work on to go to the next project but you are almost there! :blush:

2022-09-16 22:02 UTC, angeluray commented on README.md
> +
**[Mandatory Requirements]**
- [ ] Hi Micronaut, I realized you have added a readme file but you are not using [microverse template](https://github.com/microverseinc/readme-template/blob/master/README.md). Kindly use this [template](https://github.com/microverseinc/readme-template/blob/master/README.md) and fill your data inside that. This readme file is the professional documentation file of your project so please take it seriously :+1:
- [ ] Please don't forget to add a license file after adding your readme file, because most of the students forget to add license :smile:

2022-09-16 22:02 UTC, angeluray commented on src/index.js
> +    document.getElementById("root"))
**[Mandatory Requirements]**
- [ ] You did not add Linters for this React project, kindly check this [Linter Documentation](https://github.com/microverseinc/linters-config) to make sure your project is problem free and follows the guidelines 👍🏼 . After you do this, your project should be ready for approval 🥇

2022-09-18 10:28 UTC, wadaudzai commented on src/index.js
> +    document.getElementById("root"))
Already done dear bro.

2022-11-23 19:07 UTC, merged